### ISSUE TITLE
Any updates on this?

### ISSUE THREAD

**Issue by 1RandomDev** [Noobgamer0111/SubwaySurfersDecrypted#9]
Has the key been found yet? I have tested a few things and noticed that you can just copy over the `/sdcard/Android/data/com.kiloo.subwaysurf/files` directory to another device where the app is installed and it will recognize it and work. (Internet disabled so no data can be exchanged with the cloud.) So for me that would be a clear sign that the key either is in the apk itself or somewhere stored in the files directory.

**Comment by Noobgamer0111** [comment]
Sorry for the late reply.

It has been confirmed that the encryption key is stored locally on your device's storage, and is present on com.kiloo.subwaysurf directory.

It has also been confirmed that the same key is used for all users. This means that if the key and IV have been found, all you need to do is plug the values into an online decrypter, and it'll spit out the values in plain/human readable.

You can help by reading the "ToDoList", and try to complete those instructions. If you're successful in any form, just hit me up with a pull request. and I'll add it to the repository.

**Comment by Aljoberg** [comment]
Sigh, I need to get back to this as well at one point 💀
